class TestFailedException(Exception):
    pass


class NoArgsException(Exception):
    pass